### ISSUE TITLE
make failing with zlib error

### ISSUE THREAD

**Issue by sourabh2k15** [cmdcolin/htslib_emscripten#1]
I ran make inside the cloned directory. I get the following error message : 

`make: *** No rule to make target /home/gbear/htslib_emscripten/zlib/libz.so, needed by htslib.  Stop. 
`
Do I need to place zlib's .so file under that directory or did I miss a previous step leading to this error ?

Please help.
Thanks.

**Comment by sourabh2k15** [comment]
Okay I ran a ./configure and make inside zlib folder that produced the zlib.so file required. After this I ran the make in the main directory

**Comment by cmdcolin** [comment]
It looks like I had a bug in the makefile. I pushed a fix, try running git pull, then git clean -fdx, then "make" (hopefully that works, you shouldn't have to manually run configure in zlib folder if all goes well)

That said, this project doesn't actually *do anything* at the moment! It does manage to compile htslib to javascript, but then there needs to be extra code to use htslib to read files.

I'd be interested to know what types of things you are trying to accomplish with it though

**Comment by cmdcolin** [comment]
I should probably clarify in the readme that the project is not currently functional...

**Comment by sourabh2k15** [comment]
Ensembl genome browser currently supports all big file formats through server side processing ( uses perl layer over htslib C library ), but is planning to switch to client side processing through javascript parsers as it will reduce server load. It has chosen Genoverse as its goto choice as it is exactly the genome browser that supports local processing of binary file formats, but the problem is Genoverse doesn't yet support all of the big file binary formats that Ensemble does. So my task is to enable that support in Genoverse.  I am trying to compile htslib into javascript so that these modules can be used in Genoverse genome browser.

I had edited the makefile manually and it does the zlib and htslib make successfully , but the last command of emcc fails with an error.

**Comment by cmdcolin** [comment]
I see! That is a very cool project. I will say unfortunately this repository's code is not currently working, and the Makefile actually is not working for me either. I can take a look at it later

There is probably not a magic bullet to help your project out, I had hoped myself that simply once you compile htslib to javascript that you could easily access the files, but I found out this is sort of difficult.

There are therefore actually two approaches

1) Use htslib code like the "htsfile" command, but what happens with this is emscripten converts the C socket code into websocket requests in javascript, and therefore, you need an extra server side program to handle websocket requests. this is in principle not that crazy but you need some extra server side code to do this (the websock_server code in this repo tries to do that)
2) Bypass all the C socket code and try to use htslib internals to parse the data formats. This would be the "pure" client side approach, but it is actually pretty challenging to use the htslib internals selectively. I asked the htslib mailing list awhile back and didn't really make any progress yet https://sourceforge.net/p/samtools/mailman/message/35602539/


Hope that helps, I'll try and take another look at this later

**Comment by sourabh2k15** [comment]
My actual task was to understand this code :
https://github.com/dasmoth/dalliance/tree/master/js , write my own modules
based on that and then add this code to Genoverse, but I thought simply
compiling through emscripten would do the job .

**Comment by cmdcolin** [comment]
cool. you might consider checking out igv.js and jbrowse as well. both igv.js and jbrowse have BAM and vcf file parsing in javascript (I am personally a fan of the jbrowse project)

also no client side javascript browser has cram support at the moment, which was the original reason for this repository to exist

**Comment by cmdcolin** [comment]
also no client side javascript browser has cram support at the moment, which was the original reason for this repository (to try to get client side cram file parsing), but it is a personal project (it is not sponsored by my work or anything)

**Comment by cmdcolin** [comment]
fixed now?

**Comment by sourabh2k15** [comment]
yup :), it wasn't an error even before. My old emcc was the trouble .
Change the status from non functional to working, it does compile , but it
depends on the user's understanding on how to use the compiled functions
hehe

**Comment by cmdcolin** [comment]
sweet. I figured it was sort of a complicated "issue" not a single topic one, but glad it's "resolved" in this sense :)
